# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['AngleX', 'AngleY', 'LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [75]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [76]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print classes

['Stand', 'Left', 'Crouch', 'Sit', 'Belly', 'Knee', 'StandInit', 'Back', 'Right', 'Frog', 'HeadBack']


In [77]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename))
    target = [i] * len(data)
    print len(data), len(target)
    return data, target

In [78]:
# load all the data
all_data = []
all_target = []

for i in range(0,len(classes)):
    data,target = load_pose_data(i)
    all_data.extend(data)
    all_target.extend(target)
    
    
print 'total number of data', len(all_data)

11 11
20 20
30 30
26 26
10 10
10 10
52 52
10 10
11 11
10 10
10 10
total number of data 200


## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [79]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.5)
training_data = permutation[:n_training_data]

In [80]:
print training_data

[129  15  72 168  67  25 161  27  58 163 121 101 119  19  56  71 183  33
 128 118  34 130 132 170 197 135 133 196  31 108  99 153  92 199  85   0
  12 149  48  21  40 173  51 195  77  61 113 112  82  39 115 131 185  60
 114 150  17 145  54 184 110  62 164 136  89  28  16  44 178 156 104   3
   8 106 100 159 187  46 126 160 111  43 177 186   1  74 169 190  45  32
  87  91  49 122 125   5 141 139 117  95]


In [81]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [82]:
fit_data = []
fit_target = []
for i in range(0,len(training_data)):
    fit_data.append(all_data[training_data[i]])
    fit_target.append(all_target[training_data[i]])
    
clf.fit(fit_data, fit_target) 

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0, degree=3,
  gamma=0.001, kernel='rbf', max_iter=-1, probability=False,
  random_state=None, shrinking=True, tol=0.001, verbose=False)

### predicting

In [83]:
clf.predict(all_data[1]), all_target[1]

(array([0]), 0)

In [84]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

## 4. Evaluate on the test data

In [85]:
expected = []
predicted = []
prediction_data = []
for i in range(0,len(all_data)):
    if( not (i in training_data)):
        expected.append(all_target[i])
        prediction_data.append(all_data[i])
predicted = clf.predict(prediction_data)

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         6
          1       1.00      1.00      1.00        11
          2       0.93      1.00      0.96        13
          3       1.00      1.00      1.00        17
          4       1.00      1.00      1.00         5
          5       1.00      1.00      1.00         5
          6       1.00      1.00      1.00        23
          7       1.00      1.00      1.00         4
          8       1.00      0.83      0.91         6
          9       1.00      1.00      1.00         5
         10       1.00      1.00      1.00         5

avg / total       0.99      0.99      0.99       100


Confusion matrix:
[[ 6  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [86]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'w'))

Then, in the application we can load the trained classifier again.

In [87]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
for i in range(0,len(all_data),5):
    print classes[clf2.predict(all_data[i])], classes[all_target[i]]

Stand Stand
Stand Stand
Stand Stand
Left Left
Left Left
Left Left
Left Left
Crouch Crouch
Crouch Crouch
Crouch Crouch
Crouch Crouch
Crouch Crouch
Crouch Crouch
Sit Sit
Sit Sit
Sit Sit
Sit Sit
Sit Sit
Belly Belly
Belly Belly
Knee Knee
Knee Knee
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
StandInit StandInit
Back Back
Back Back
Right Right
Right Right
Frog Frog
Frog Frog
HeadBack HeadBack
HeadBack HeadBack


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:3: DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  app.launch_new_instance()
